In [1]:
import pandas as pd

## Series

In [2]:
s = pd.Series(data=[1,2,3], index=['r1', 'r2', 'r3'])

print(s)
print(s.values, s.index)

r1    1
r2    2
r3    3
dtype: int64
[1 2 3] Index(['r1', 'r2', 'r3'], dtype='object')


## DataFrame

In [3]:
# columns based storage

In [4]:
df = pd.DataFrame(data=[[1,2,3], [4,5,6]], columns=['c1', 'c2', 'c3'], index=['r1', 'r2'])

print(df)

    c1  c2  c3
r1   1   2   3
r2   4   5   6


In [5]:
cols = ['c1', 'c2', 'c3']
list_of_series = [pd.Series([1,2,3],index=cols), pd.Series([4,5,6],index=cols)]
df = pd.DataFrame(list_of_series, columns=cols, index=['r1', 'r2'])

print(df)
print(df.values)

    c1  c2  c3
r1   1   2   3
r2   4   5   6
[[1 2 3]
 [4 5 6]]


### Primary Indexing

In [6]:
# select columns

In [7]:
print(df['c1'], df['c1'].values)

print(df[['c1', 'c2']])

type(df['c1'].values)

r1    1
r2    4
Name: c1, dtype: int64 [1 4]
    c1  c2
r1   1   2
r2   4   5


numpy.ndarray

### Implicit Indexing

In [8]:
# 1. 0-based
# 2. lower included - upper excluded
# 3. Pure Integer based

In [9]:
print(df)

print(df.iloc[1])
print(df.iloc[1, 2])

    c1  c2  c3
r1   1   2   3
r2   4   5   6
c1    4
c2    5
c3    6
Name: r2, dtype: int64
6


### Explicit Indexing

In [10]:
# 1. Pure label based
# 2. lower and upper included

In [11]:
print(df.loc[:'r2'])
print(df.loc['r1', 'c2':'c3'])

    c1  c2  c3
r1   1   2   3
r2   4   5   6
c2    2
c3    3
Name: r1, dtype: int64
